### ISSUE TITLE
The RabbitMQ container keeps getting killed when deploying Docker Compose with partitions

### ISSUE THREAD

**Issue by junh-ki** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#20]
I fixed the issue by replacing the healthcheck argument, `status`, with `cluster_status`.

```yml
healthcheck:
      test: ["CMD", "rabbitmqctl", "cluster_status"]
      interval: 5s
      timeout: 2s
      retries: 60
```

Otherwise, the RabbitMQ container will keep getting killed. 
I am still not sure why this is the case.
Does anyone have an idea?
